language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby

matrix:
  fast_finish: true
  allow_failures:
    - php: jruby
  exclude:
    - rvm: jruby
      env: KITCHEN_SINK=1

sudo: false

env:
  - PURE_RUBY=1
  - KITCHEN_SINK=1

# before_script:

script:
  - 'bundle install --without docs'
  - 'ruby tests.rb'

# after_script:

notifications:
  email:
    - 'ryan.parman@wepay.com'
