language: ruby

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-head
  - rbx-head
  - mruby-head
  - ironruby-head
  - goruby
  - topaz

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head
    - rvm: mruby-head
    - rvm: ironruby-head
    - rvm: goruby
    - rvm: topaz

sudo: false

bundler_args: --without docs

# before_script:

script:
  - 'bundle install --without docs'
  - 'ruby tests.rb'

# after_script:

notifications:
  email:
    - 'ryan.parman@wepay.com'
